### ISSUE TITLE
Create textures and models for all blocks and add them without functionality

### ISSUE THREAD

**Issue by BitTim** [TheBluebits/Project-Hong-Taiyang#4]
Create textures and models (If needed) for all these blocks and add them to the codebase without adding extra functionality for now. They just need to be placeable and breakable in creative mode.

### Todo
- [ ] Umbral Ore (Overlay for resonating state)
- [ ] Deepslare Umbral Ore (Overlay for resonating state)
- [ ] Block of Umbral
- [ ] Darkdweller Root
- [ ] Darkdweller Log
- [ ] Darkdweller Stick
- [ ] Darkdweller Planks
- [ ] Darkdweller Slab
- [ ] Darkdweller Stairs
- [ ] Darkdweller Fence
- [ ] Darkdweller Fence Gate
- [ ] Darkdweller Door
- [ ] Darkdweller Trapdoor
- [ ] Darkdweller Button
- [ ] Darkdweller Pressure Plate
- [ ] Darkdweller Sign
- [ ] Sculk Soil
- [ ] Rooted Sculk Soil

### In Progress
- [ ] Darkdweller Bundle
- [ ] Stripped Darkdweller Bundle

### Finished

**Comment by BitTim** [comment]
This issue is now obsolete and has been merged
- #33 
- #34
